model: lstm

# Dataset
data_path: datasets/coraa-ser  # Path to the dataset
class_labels: ["neutral", "non-neutral-female", "non-neutral-male"]  # Emotion labels
# Alternative class labels
# class_labels: ["positive", "negative", "neutral"]
# class_labels: ["angry", "boredom", "disgust", "fear", "happy", "neutral", "sad"]

# Features
feature_folder: features/6-category/opensmile_casia/  # Folder to store features
feature_method: o  # 'o': opensmile, 'l': librosa  # Method for feature extraction

# Opensmile Configuration (needed only if 'feature_method' is 'o')
opensmile_config: IS10_paraling  # Opensmile standard feature set
opensmile_path: /home/lettuce/code/extra/opensmile-2.3.0 # Path to Opensmile installation

# Checkpoints
checkpoint_path: checkpoints/  # Path to store checkpoints
checkpoint_name: LSTM_OPENSMILE_IS10  # Checkpoint file name

# Training Parameters
epochs: 20  # Number of epochs for training
batch_size: 32  # Batch size
lr: 0.001  # Learning rate

# Model Parameters
rnn_size: 128  # LSTM hidden layer size
hidden_size: 32  # Fully connected layer size
dropout: 0.5  # Dropout rate
